<?php
/**
 * Created by PhpStorm.
 * User: wb5398
 * Date: 2020-07-09
 * Time: 오후 5:46
 */

namespace Controller\Front\Member;

use Framework\Debug\Exception\AlertRedirectException;
use Session;
use Request;
use Component\Member\Member;
use Component\Webidas\Webidas;

class JoinOkController extends \Bundle\Controller\Front\Member\JoinOkController
{
    public function index()
    {
        try {
            parent::index(); // TODO: Change the autogenerated stub
            //Webidas::dumper(Session::get(Member::SESSION_DREAM_SECURITY));
            $this->setData('memNo', $this->getData('memNo')=='' ? Request::get()->get('memNo'):$this->getData('memNo'));
            $this->setData('isCBT', Webidas::isInspect(true) ? 'y':'n');
            $ssgdfmAction = 'n';
            if($this->getData('memNo')) {
                /** @var  \Component\Webidas\SsgdfmDataProxy $dataProxy */
                $dataProxy = \App::load('\\Component\\Webidas\\SsgdfmDataProxy');
                $sendFl = $dataProxy->getSendFl($this->getData('memNo'));
                $ssgdfmAction = $sendFl['ssgdfmFl'] == 'r' ? 'y':'n';
            }
            $this->setData('ssgdfmAction', $ssgdfmAction);
        } catch (AlertRedirectException $e) {
            throw $e;
        }

    }
}